#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require_relative 'hbase.thrift_types'

module Apache
  module Hadoop
    module Hbase
      module Thrift2
      end
    end
  end
end
